---
- name: Deploy task
  hosts: all
  vars:
    ansistrano_deploy_from: "./"
    ansistrano_deploy_to: "/var/www/deploy_test"
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: git@github.com:USERNAME/REPO.git
    ansistrano_git_branch: master
    ansistrano_git_identity_key_path: ""
    ansistrano_keep_releases: 3
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }

